- name: play level variables
  hosts: local
  connection: local
  vars:
    COURSE: Ansible
    DURATION: 10HR
    TRAINER: GP
  tasks:
  - name: print course infromation
    ansible.builtin.debug:
    msg: "Hello {{ COURSE }}, Course Duration: {{ DURATION }}, trainer is {{ TRAINER }}"